server:
  port: 8081

spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/product?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

